export const tv_broad_reports = [
  {
    id: 1,
    image: "/images/daily-summary-report.png",
    title: "Daily Summary",
    lastUpdated: "April 15, 2024",
    page: "tv",
    subpage: "broadcasters",
    slug: "daily-summary-report",
  },
  {
    id: 2,
    image: "/images/audience-insights.png",
    title: "Audience Insights",
    lastUpdated: "April 20, 2024",
    page: "tv",
    subpage: "broadcasters",
    slug: "audience-insights",
  },
  {
    id: 3,
    image: "/images/revenue-insights.png",
    title: "Revenue Insights",
    lastUpdated: "April 25, 2024",
    page: "tv",
    subpage: "broadcasters",
    slug: "revenue-insights",
  },
  {
    id: 4,
    image: "/images/competitive-landscape.png",
    title: "Competitive Landscape",
    lastUpdated: "May 1, 2024",
    page: "tv",
    subpage: "broadcasters",
    slug: "competitive-landscape",
  },
  {
    id: 5,
    image: "/images/channel-specific-reports.png",
    title: "Channel Specific Reports",
    lastUpdated: "May 10, 2024",
    page: "tv",
    subpage: "broadcasters",
    slug: "channel-specific-reports",
  },
  {
    id: 6,
    image: "/images/language-specific-reports.png",
    title: "Language Specific Reports",
    lastUpdated: "May 15, 2024",
    page: "tv",
    subpage: "broadcasters",
    slug: "language-specific-reports",
  },
];

export const tv_ads_reports = [
  {
    id: 1,
    image: "/images/content-performance.png",
    title: "Content Performance",
    lastUpdated: "April 15, 2024",
    page: "tv",
    subpage: "ads",
    slug: "content-performance",
  },
  {
    id: 2,
    image: "/images/audience-demographics.png",
    title: "Audience Demographics",
    lastUpdated: "March 31, 2024",
    page: "tv",
    subpage: "ads",
    slug: "audience-demographics",
  },
  {
    id: 3,
    image: "/images.png",
    title: "Ad Spend Analysis",
    lastUpdated: "April 10, 2024",
    page: "tv",
    subpage: "ads",
    slug: "ad-spend-analysis",
  },
  {
    id: 4,
    image: "/images.png",
    title: "Ad Placement Trends",
    lastUpdated: "April 20, 2024",
    page: "tv",
    subpage: "ads",
    slug: "ad-placement-trends",
  },
  {
    id: 5,
    image: "/images.png",
    title: "Return on Ad Spend (ROAS) Insights",
    lastUpdated: "April 25, 2024",
    page: "tv",
    subpage: "ads",
    slug: "roas-insights",
  },
  {
    id: 6,
    image: "/images.png",
    title: "Ad Frequency Analysis",
    lastUpdated: "April 30, 2024",
    page: "tv",
    subpage: "ads",
    slug: "ad-frequency-analysis",
  },
  {
    id: 7,
    image: "/images.png",
    title: "Ad Engagement Metrics",
    lastUpdated: "May 5, 2024",
    page: "tv",
    subpage: "ads",
    slug: "ad-engagement-metrics",
  },
  {
    id: 8,
    image: "/images.png",
    title: "Prime-Time Ad Analysis",
    lastUpdated: "May 10, 2024",
    page: "tv",
    subpage: "ads",
    slug: "prime-time-ad-analysis",
  },
];

export const tv_brands_reports = [
  {
    id: 1,
    image: "/images/brands.png",
    title: "Top Performing Brands",
    lastUpdated: "April 10, 2024",
    page: "tv",
    subpage: "brands",
    slug: "top-performing-brands",
  },
  {
    id: 2,
    image: "/images/brands.png",
    title: "Brand Awareness Trends",
    lastUpdated: "April 15, 2024",
    page: "tv",
    subpage: "brands",
    slug: "brand-awareness-trends",
  },
  {
    id: 3,
    image: "/images/brands.png",
    title: "Brand Recall Metrics",
    lastUpdated: "April 20, 2024",
    page: "tv",
    subpage: "brands",
    slug: "brand-recall-metrics",
  },
  {
    id: 4,
    image: "/images/brands.png",
    title: "Market Share Analysis",
    lastUpdated: "April 25, 2024",
    page: "tv",
    subpage: "brands",
    slug: "market-share-analysis",
  },
  {
    id: 5,
    image: "/images/brands.png",
    title: "Customer Loyalty Insights",
    lastUpdated: "April 30, 2024",
    page: "tv",
    subpage: "brands",
    slug: "customer-loyalty-insights",
  },
  {
    id: 6,
    image: "/images/brands.png",
    title: "Brand Engagement Analysis",
    lastUpdated: "May 5, 2024",
    page: "tv",
    subpage: "brands",
    slug: "brand-engagement-analysis",
  },
  {
    id: 7,
    image: "/images/brands.png",
    title: "Emerging Brands Report",
    lastUpdated: "May 10, 2024",
    page: "tv",
    subpage: "brands",
    slug: "emerging-brands-report",
  },
];

export const getReportBySlug = (slug, type) => {
  const allReports = {
    tv_broad_reports,
    tv_ads_reports,
    tv_brands_reports,
  };

  return allReports[type]?.find((report) => report.slug === slug);
};
